#!/bin/bash

# This script automatically creates/updates .env files for client and server
# based on GitHub Codespaces environment variables.
# Assumes this script is run from the project root directory.

echo "--- Starting automatic environment variable configuration for Codespaces ---"

# Check if the necessary environment variables exist
if [ -z "$CODESPACE_NAME" ] || [ -z "$GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN" ]; then
  echo "Error: CODESPACE_NAME or GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN environment variables not found."
  echo "This script is intended to run inside a GitHub Codespace."
  exit 1
fi

# Construct URLs based on Codespaces environment variables
FRONTEND_PORT="3000"
BACKEND_PORT="5000"
# Ensure HTTPS is used for Codespaces URLs
FRONTEND_URL="https://${CODESPACE_NAME}-${FRONTEND_PORT}.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
BACKEND_URL="https://${CODESPACE_NAME}-${BACKEND_PORT}.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"

echo "Detected Frontend URL: ${FRONTEND_URL}"
echo "Detected Backend URL: ${BACKEND_URL}"

# --- Configure Backend (server/.env) ---
# Get the directory where the script is located (should be the project root)
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
# Construct the path relative to the script directory (project root)
SERVER_ENV_FILE="$SCRIPT_DIR/server/.env" # Path from root: ./server/.env

# Check if server directory exists
if [ ! -d "$SCRIPT_DIR/server" ]; then
    echo "Error: Directory '$SCRIPT_DIR/server' not found."
    exit 1
fi

echo "Updating ${SERVER_ENV_FILE}..."
# Overwrite or create the .env file for the server
{
  echo "# Auto-generated by set-env.sh"
  echo "PORT=${BACKEND_PORT}"
  echo "CORS_ORIGIN=${FRONTEND_URL}"
} > "$SERVER_ENV_FILE"
# Check if write was successful (optional)
if [ $? -ne 0 ]; then
    echo "Error: Failed to write to ${SERVER_ENV_FILE}"
    exit 1
fi
echo "-> Updated ${SERVER_ENV_FILE}"

# --- Configure Frontend (client/.env) ---
# Construct the path relative to the script directory (project root)
CLIENT_ENV_FILE="$SCRIPT_DIR/client/.env" # Path from root: ./client/.env

# Check if client directory exists
if [ ! -d "$SCRIPT_DIR/client" ]; then
    echo "Error: Directory '$SCRIPT_DIR/client' not found."
    exit 1
fi

echo "Updating ${CLIENT_ENV_FILE}..."
# Overwrite or create the .env file for the client
{
  echo "# Auto-generated by set-env.sh"
  echo "VITE_API_URL=${BACKEND_URL}"
} > "$CLIENT_ENV_FILE"
# Check if write was successful (optional)
if [ $? -ne 0 ]; then
    echo "Error: Failed to write to ${CLIENT_ENV_FILE}"
    exit 1
fi
echo "-> Updated ${CLIENT_ENV_FILE}"

echo "--- Automatic environment variable configuration complete ---"

exit 0
